### ISSUE TITLE
Does SCEVAN have a requirement for the minimum number of cells?

### ISSUE THREAD

**Issue by BioAmelie** [AntonioDeFalco/SCEVAN#105] opened 2024-03-03 02:49 UTC
@AntonioDeFalco 
Hi author,

I occured the error : Error in data.frame(x = tsne$Y[, 1], y = tsne$Y[, 2], Subclones = pred) , when I run SCEVAN. This samples have 60 cells. 

Is it because the number of cells is too low?

**Comment by AntonioDeFalco** [comment] 2024-03-10 16:47
Hi @BioAmelie,
It is difficult to understand the problem from the error reported, but it most likely due to the small number of cells in the sample. I think using subclonal analysis with this number of cells is a bit excessive. Is it a Smart-seq2 sample?

Regards.

**Comment by AntonioDeFalco** [comment] 2024-03-10 17:00
Duplicate of https://github.com/AntonioDeFalco/SCEVAN/issues/99

**Closed by AntonioDeFalco** 2024-03-10 17:00 UTC
